import "dotenv/config";
import Fastify from "fastify";
import cors from "@fastify/cors";
import bcrypt from "bcrypt";
import { userRoutes } from "./modules/user/user.routes.js";
import { authRoutes } from "./modules/auth/auth.routes.js";
import { prisma } from "./db/prisma.js";
import { postRoutes } from "./modules/post/post.routes.js";

const app = Fastify();


async function seedTestData() {
  let user = await prisma.user.findUnique({
    where: { login: "test" },
  });

  if (!user) {
    const hashedPassword = await bcrypt.hash("test", 10);

    user = await prisma.user.create({
      data: {
        login: "test",
        email: "test@test.com",
        name: "Test User",
        password: hashedPassword,
      },
    });

    console.log("✅ Test user created");
  }

  const usersCount = await prisma.user.count();

  let users = [];

  if (usersCount < 20) {
    const hashedPassword = await bcrypt.hash("test", 10);

    users = await Promise.all(
      Array.from({ length: 20 }).map((_, i) =>
        prisma.user.create({
          data: {
            login: `user${i + 1}`,
            email: `user${i + 1}@test.com`,
            name: `User ${i + 1}`,
            password: hashedPassword,
          },
        })
      )
    );

    console.log("✅ 20 users created");
  } else {
    users = await prisma.user.findMany();
  }

  const tagNames = ["frontend", "backend", "prisma", "fastify", "react"];

  const tags = await Promise.all(
    tagNames.map((name) =>
      prisma.tag.upsert({
        where: { name },
        update: {},
        create: { name },
      })
    )
  );

  console.log("✅ Tags ready");

  const postsCount = await prisma.post.count();

  if (postsCount === 0) {
    const BATCH_SIZE = 10;
    const TOTAL_POSTS = 100;

    for (let i = 0; i < TOTAL_POSTS; i += BATCH_SIZE) {
      const batch = Array.from({ length: BATCH_SIZE }).map((_, j) => {
        const index = i + j;
        const user = users[index % users.length];

        return prisma.post.create({
          data: {
            title: `Post #${index + 1}`,
            content: `This is autogenerated post ${index + 1}`,
            imageUrl: `https://picsum.photos/seed/${index + 1}/600/400`,
            userId: user.id,
          },
        });
      });

      await Promise.all(batch);
    }

    console.log("✅ 100 posts created");
  }

  const posts = await prisma.post.findMany();

  const relationsExist = await prisma.postTag.count();

  if (relationsExist === 0) {
    const relations: { postId: number; tagId: number }[] = [];

    for (const post of posts) {
      const randomTags = tags
        .sort(() => Math.random() - 0.5)
        .slice(0, Math.floor(Math.random() * 3) + 1);

      for (const tag of randomTags) {
        relations.push({
          postId: post.id,
          tagId: tag.id,
        });
      }
    }

    await prisma.postTag.createMany({
      data: relations,
    });

    console.log("✅ PostTag relations created");
  }
}

async function registerPlugins() {
  await app.register(cors, {
    origin: "http://localhost:5173",
    credentials: true,
  });
}


async function registerRoutes() {
  await app.register(userRoutes);
  await app.register(authRoutes);
  await app.register(postRoutes);
}


function setupErrorHandler() {
  app.setErrorHandler((error, req, reply) => {
    const status = (error as any).statusCode ?? 500;

    reply.status(status).send({
      error: error.message,
    });
  });
}


async function start() {
  try {
    await registerPlugins();
    await registerRoutes();
    setupErrorHandler();

    await app.listen({ port: 3301 });

    console.log("🚀 Server running on http://localhost:3301");

    await seedTestData();
  } catch (err) {
    console.error(err);
    process.exit(1);
  }
}

start();

process.on("SIGINT", async () => {
  await prisma.$disconnect();
  process.exit(0);
});
